<a href="https://colab.research.google.com/github/jparkgit/NumPy/blob/master/HW1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HW I (Numpy): 마감기한 09/19 화요일 23:59
1903055 - 생명과학과 - 박지현

In [1]:
import numpy as np

#### 1. For an 2-dimensional input matrix, write a NumPy function to subtract the mean of each row of a given matrix.
```
Sample Input:
A = np.array([[1,2,5,1], [3,4,1,0]])
my_function(A)
Sample Output:
array([[-1.25, -0.25, 2.75, -1.25],
       [1. , 2. ,-1. ,-2. ]])
```



hint: broadcasting

In [ ]:
A = np.array([[1,2],
              [10,20]])
A

array([[ 1,  2],
       [10, 20]])

In [ ]:
# mean of each row
row_mean = A.mean(axis=1)
row_mean

array([ 1.5, 15. ])

In [ ]:
row_mean_reshape = row_mean.reshape([row_mean.shape[0],1])
row_mean_reshape

array([[ 1.5],
       [15. ]])

In [ ]:
# correctly broadcasted
A - row_mean_reshape

array([[-0.5,  0.5],
       [-5. ,  5. ]])

In [ ]:
def my_function(A):
  mean = A.mean(axis=1)
  myreturn = A - mean.reshape([mean.shape[0],1])
  return myreturn

In [ ]:
my_function(A)

array([[-0.5,  0.5],
       [-5. ,  5. ]])

#### 2. For an 2-dimensional input matrix, write a NumPy function to subtract the mean of each column of a given matrix.

In [ ]:
# mean of each row
col_mean = A.mean(axis=0)
col_mean

array([ 5.5, 11. ])

col_mean은 row_mean과 다르게 reshape이 필요없다.\
첫번째 column에서는 col_mean의 첫번째 element를 행을 따라 계속 빼줄 것이기 때문이다.\
확인하기 위해서는 broadcasting이 올바로 되기 위해 col_mean 1차원 array를 [1,n] 2차원 array로 reshape해서 뺄셈을 적용시켜볼 수 있다.

In [ ]:
A - col_mean

array([[-4.5, -9. ],
       [ 4.5,  9. ]])

In [ ]:
A - col_mean.reshape([1, col_mean.shape[0]])

array([[-4.5, -9. ],
       [ 4.5,  9. ]])

결과값이 똑같이 옳게 나오는 것을 확인할 수 있다. 따라서 reshape는 생략해도 된다.

In [ ]:
def my_function2(A):
  mean = A.mean(axis=0)
  myreturn = A - mean
  return myreturn

In [ ]:
my_function2(A)

array([[ -4.5,  -9. , -13.5],
       [  4.5,   9. ,  13.5]])

#### 3. Write a NumPy function to concatenate two given two dimensional arrays of shape (n, p) and (n,q), respectively, to create (n, p+q) array.

In [ ]:
def my_function3(arr1,arr2):
  myreturn = np.concatenate((arr1, arr2), axis=1)
  return myreturn

In [ ]:
A = np.array([[1,2],
              [10,20]])
B = np.array([[1,2,3],
              [10,20,30]
             ])
my_function3(A,B)

array([[ 1,  2,  1,  2,  3],
       [10, 20, 10, 20, 30]])

In [ ]:
print(A.shape)
print(B.shape)
print(my_function3(A,B).shape)

(2, 2)
(2, 3)
(2, 5)


#### 4. Write a NumPy function to concatenate two given two dimensional arrays of shape (n, p) and (m,p), respectively, to create (n+m, p) array.

In [ ]:
def my_function4(arr1,arr2):
  myreturn = np.concatenate((arr1, arr2), axis=0)
  return myreturn

In [ ]:
A = np.array([[1,2,3],
              [10,20,30]])
B = np.array([[1,2,3],
              [10,20,30],
              [100,200,300]])
my_function4(A,B)

array([[  1,   2,   3],
       [ 10,  20,  30],
       [  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

In [ ]:
print(A.shape)
print(B.shape)
print(my_function4(A,B).shape)

(2, 3)
(3, 3)
(5, 3)



#### 5. [Video Record] Create a python function to create a matrix having a boundary with a value of 1 and an inner one 0 the legend is shown below for given row and column numbers:

풀이: https://youtu.be/sSsyF4apSE4

In [17]:
arr = np.ones([5,5])
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
arr[1:-1, 1:-1] = 0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
def my_function5(row,col):
  arr = np.ones([row,col])
  arr[1:-1,1:-1]=0
  return arr

In [10]:
my_function5(5,4)

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

#### 6. Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.\
The moving averages with k=4 of a ten-value sequence (n=10) is shown below\
 i 1 2 3 4 5 6 7 8 9 10\
===== == == == == == == == == == ==\
```
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
```
Thus, the moving average sequence has n-k+1=10-4+1=7 values.\
Write a Python function to find moving average in an array over a window with an array and window size as inputs:\
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window size 3.

In [ ]:
def my_function6(array, k):
  len = array.shape[0] - k + 1
  avg = np.ones([len])
  for i in range(len):
    temp = array[i: i+k]
    avg[i] = temp.mean()
  return avg

In [ ]:
my_function6(np.array([10,20,30,40,50,60,70,80,90,100]), 4)

array([25., 35., 45., 55., 65., 75., 85.])

In [ ]:
array = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
my_function6(array,3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])

#### 7 [Video Record] You are given the following information of drivers:

풀이: https://youtu.be/TICXqAB2Tw4

In [ ]:
# Number of accidents
T1 = np.array([[0,1,0,1,2],
               [1,3,2,1,0],
               [0,0,0,1,3]])
# Salary
T2 = np.array([[157,167,130,145,170],
               [250,260,263,273,290],
               [301,120,30,100,502]])
# Sports car
T3 = np.array([[1,1,1,1,1],
               [0,0,0,0,0],
               [0,0,0,0,0]])

Make (3,5,2) where (i,j,k) represents (i-th person, j-th year, k) where\
k=0 = 건수\
k=1 = salary


In [ ]:
# final array shape: [3,5,2]
# stack 3 arrays of [year, k] of each person
df1 = np.ones([3,5,2])
for i in range(3): # i-th person
  for j in range(5): # j-th year
    df1[i,j,0] = T1[i, j] # number of accidents
    df1[i,j,1] = T2[i, j] # salary
df1

array([[[  0., 157.],
        [  1., 167.],
        [  0., 130.],
        [  1., 145.],
        [  2., 170.]],

       [[  1., 250.],
        [  3., 260.],
        [  2., 263.],
        [  1., 273.],
        [  0., 290.]],

       [[  0., 301.],
        [  0., 120.],
        [  0.,  30.],
        [  1., 100.],
        [  3., 502.]]])

In [ ]:
B = np.stack([T1,T2], axis=2)
print(B.shape)
print(B)

(3, 5, 2)
[[[  0 157]
  [  1 167]
  [  0 130]
  [  1 145]
  [  2 170]]

 [[  1 250]
  [  3 260]
  [  2 263]
  [  1 273]
  [  0 290]]

 [[  0 301]
  [  0 120]
  [  0  30]
  [  1 100]
  [  3 502]]]


a. Create an array “N” of shape [3, 5] to represent the number of accidents. Similarly, create arrays of “Salary” and “Sports” of shape [3,5] each to represent the salary and sports car.

In [12]:
# Number of accidents
N = np.array([[0,1,0,1,2],
               [1,3,2,1,0],
               [0,0,0,1,3]])
# Salary
Salary = np.array([[157,167,130,145,170],
               [250,260,263,273,290],
               [301,120,30,100,502]])
# Sports car
Sports = np.array([[1,1,1,1,1],
               [0,0,0,0,0],
               [0,0,0,0,0]])

b. Create an array “Y” of shape [3,5,3] where \
(i,j,1)-th element of “Y” represent the number of accidents of i-th id in the j-th year, and \
(i,j,2)-th element of “Y” represents the salary of i-th id in the j-th year, and \
(i,j,3)-th element of “Y” represent sports car (0 or 1) of i-th id in the j-th year. \
(Please type everything element to define “Y”)

In [ ]:
Y = np.array([[[0, 157, 1], # 0th ID, Year 1
              [1, 167, 1],     # Year 2: [Number of accidents, salary, sports car]
              [0, 130, 1],     # Year 3:  ""
              [1, 145, 1],
              [2, 170, 1]],
             [[1, 250, 0], # 1st ID, Year 1
              [3, 260, 0],      # Year 2:
              [2, 263, 0],
              [1, 273, 0],
              [0, 290, 0]],
             [[0, 301, 0], # 2nd ID
              [0, 120, 0],
              [0,  30, 0],
              [1, 100, 0],
              [3, 502, 0]]])
print(Y.shape)
print(Y)

(3, 5, 3)
[[[  0 157   1]
  [  1 167   1]
  [  0 130   1]
  [  1 145   1]
  [  2 170   1]]

 [[  1 250   0]
  [  3 260   0]
  [  2 263   0]
  [  1 273   0]
  [  0 290   0]]

 [[  0 301   0]
  [  0 120   0]
  [  0  30   0]
  [  1 100   0]
  [  3 502   0]]]


c. Solve part b> again by utilizing “N”, “Salary”, and “Sports” defined in (a).

In [13]:
Y = np.stack([N,Salary, Sports], axis=2)
print(Y.shape)
print(Y)

(3, 5, 3)
[[[  0 157   1]
  [  1 167   1]
  [  0 130   1]
  [  1 145   1]
  [  2 170   1]]

 [[  1 250   0]
  [  3 260   0]
  [  2 263   0]
  [  1 273   0]
  [  0 290   0]]

 [[  0 301   0]
  [  0 120   0]
  [  0  30   0]
  [  1 100   0]
  [  3 502   0]]]


d. Create an array “Y2” of shape [3,3,5] where\
(i,1,j)-th element of “Y” represent the number of accidents of i-th id in the j-th year, and \
(i,2,j)-th element of “Y” represents the salary of i-th id in the j-th year, and\
(i,3,j)-th element of “Y” represent sports car (0 or 1) of i-th id in the j-th year.\
(Please type everything element to define “Y2”)

In [ ]:
Y2 = np.array([[[0, 1, 0, 1, 2],              # number of accidents
                [157, 167, 130, 145, 170],    # salary
                [1, 1, 1, 1, 1]],             # sports car
               [[1, 3, 2, 1, 0],          # [year1, 2, 3, 4, 5]
                [250, 260, 263, 273, 290],
                [0, 0, 0, 0, 0]],
               [[0, 0, 0, 1, 3],          # 2rd ID
                [301, 120,  30, 100, 502],
                [0, 0, 0, 0, 0]]])
Y2

array([[[  0,   1,   0,   1,   2],
        [157, 167, 130, 145, 170],
        [  1,   1,   1,   1,   1]],

       [[  1,   3,   2,   1,   0],
        [250, 260, 263, 273, 290],
        [  0,   0,   0,   0,   0]],

       [[  0,   0,   0,   1,   3],
        [301, 120,  30, 100, 502],
        [  0,   0,   0,   0,   0]]])

e. Solve part d> again by converting an array “Y” into “Y2”\
Hint: Use numpy.tranpose() function or numpy.swapaxes() function

In [15]:
np.transpose(Y, [0,2,1]) # [3,5,3] -> [3,3,5]
                         # [0,1,2] -> [0,2,1]

array([[[  0,   1,   0,   1,   2],
        [157, 167, 130, 145, 170],
        [  1,   1,   1,   1,   1]],

       [[  1,   3,   2,   1,   0],
        [250, 260, 263, 273, 290],
        [  0,   0,   0,   0,   0]],

       [[  0,   0,   0,   1,   3],
        [301, 120,  30, 100, 502],
        [  0,   0,   0,   0,   0]]])

In [16]:
np.swapaxes(Y, 2, 1)

array([[[  0,   1,   0,   1,   2],
        [157, 167, 130, 145, 170],
        [  1,   1,   1,   1,   1]],

       [[  1,   3,   2,   1,   0],
        [250, 260, 263, 273, 290],
        [  0,   0,   0,   0,   0]],

       [[  0,   0,   0,   1,   3],
        [301, 120,  30, 100, 502],
        [  0,   0,   0,   0,   0]]])

f. Solve part d> again by utilizing “N”, “Salary”, and “Sports” defined in (a).


In [14]:
Y2 = np.stack([N,Salary, Sports], axis=1)
print(Y2.shape)
print(Y2)

(3, 3, 5)
[[[  0   1   0   1   2]
  [157 167 130 145 170]
  [  1   1   1   1   1]]

 [[  1   3   2   1   0]
  [250 260 263 273 290]
  [  0   0   0   0   0]]

 [[  0   0   0   1   3]
  [301 120  30 100 502]
  [  0   0   0   0   0]]]
