<a href="https://colab.research.google.com/github/jparkgit/NumPy/blob/master/%ED%86%B5%EC%88%98_HW7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import numpy as np
import scipy

#9

In [2]:
A = np.array([[2,-1,0],
              [-1,2,0],
              [0,0,1]])
A

array([[ 2, -1,  0],
       [-1,  2,  0],
       [ 0,  0,  1]])

In [5]:
a = np.linalg.eig(A)
a

(array([3., 1., 1.]), array([[ 0.70710678,  0.70710678,  0.        ],
        [-0.70710678,  0.70710678,  0.        ],
        [ 0.        ,  0.        ,  1.        ]]))

In [9]:
D = np.array([[3,0,0],
              [0,1,0],
              [0,0,1]])
P = a[1]
invP = np.linalg.inv(P)

In [16]:
np.matmul(np.matmul(P,D), invP)

array([[ 2., -1.,  0.],
       [-1.,  2.,  0.],
       [ 0.,  0.,  1.]])

#10

##1

In [30]:
A1 = np.array([[2,1],
              [1,2]])

In [31]:
np.linalg.eig(A1)
# Are all eigenvalues are greater than 0? YES
# A1 is positive definite

(array([3., 1.]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

##2

In [32]:
A2 = np.array([[2,3],
              [3,2]])

In [33]:
np.linalg.eig(A2)
# Are all eigenvalues are greater than 0? NO
# A2 is not positive definite

(array([ 5., -1.]), array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

##3

In [34]:
A3 = np.array([[2,-1,0],
              [-1,2,0],
              [0,0,1]])

In [35]:
np.linalg.eig(A3)
# Are all eigenvalues are greater than 0? YES
# A3 is positive definite

(array([3., 1., 1.]), array([[ 0.70710678,  0.70710678,  0.        ],
        [-0.70710678,  0.70710678,  0.        ],
        [ 0.        ,  0.        ,  1.        ]]))